# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/12_data.external.ipynb.

# %% ../../nbs/12_data.external.ipynb 2
from __future__ import annotations
from fastdownload import FastDownload
from functools import lru_cache
from ..imports import *
import xcube.data

# %% auto 0
__all__ = ['xcube_cfg', 'xcube_path', 'XURLs']

# %% ../../nbs/12_data.external.ipynb 7
@lru_cache(maxsize=None)
def xcube_cfg() -> Config: # Config that contains default download paths for `data`, `model`, `storage` and `archive`
    "`Config` object for xcube's `config.ini`"
    return Config(Path(os.getenv('XCUBE_HOME', '~/.xcube')), 'config.ini', create=dict(
        data = 'data', archive = 'archive', storage = 'tmp', model = 'models'))

# %% ../../nbs/12_data.external.ipynb 10
def xcube_path(folder:str) -> Path: 
    "Local path to `folder` in `Config`"
    return xcube_cfg().path(folder)

# %% ../../nbs/12_data.external.ipynb 13
class XURLs():
    "Global cosntants for datasets and model URLs."
    LOCAL_PATH = Path.cwd()
    S3 = 'https://xcubebucket.s3.us-east-2.amazonaws.com/'
    
    #main datasets
    MIMIC3 = ''
    MIMIC3_L2R = f'{S3}mimic/mimic3.tgz'
    
    def path(
        url:str='.', # File to download
        c_key:str='archive' # Key in `Config` where to save URL
    ) -> Path:
        "Local path where to download based on `c_key`"
        fname = url.split('/')[-1]
        local_path = XURLs.LOCAL_PATH/('models' if c_key=='model' else 'data')/fname
        if local_path.exists(): return local_path
        return xcube_path(c_key)/fname
