#!/bin/bash

# Include the parameter parsing function
source param_parser.sh

# Initialize parameters with default values
fname="mimic3-9k_clas_4500"
plant=false
infer=0

# Parse named parameters
parse_params "$@"

# Check and use string and boolean parameters
echo "fname is: $fname"
echo "infer is: $infer"

if [ "$plant" = true ]; then
    echo "plant is true"
else
    echo "plant is false"
fi

accelerate launch --mixed_precision=fp16 --num_processes=1 \
                                    train.py \
                                    --data="mimic3-9k_4500" \
                                    --fp16 \
                                    --workers=16 \
                                    --track_train \
                                    --log \
                                    --lm \
                                    --epochs="[10, 8, 8, 8, 0]" \
                                    --lrs="[(3e-2,1e-3), (1e-2,1e-3), (1e-2, 1e-3), (1e-2,1e-3), (1e-6,1e-6)]" \
                                    --fit_sgdr \
                                    --lrs_sgdr="[(0.15,1e-3), (1e-2,1e-3), (1e-2, 1e-3), (1e-2,1e-3), (1e-6,1e-6)]" \
                                    --bs=16 \
                                    --save_model \
                                    --fname=$fname \
                                    --runs=1 \
                                    --plant=$plant \
                                    --attn_init="(0,1,1)" \
                                    --infer=$infer \
                                    --metrics="partial(precision_at_k, k=5); partial(precision_at_k, k=8); partial(precision_at_k, k=15)"
echo "files created:"
find .. -name "$fname*" 
