#!/bin/bash

# Include the parameter parsing function
source param_parser.sh

# Initialize parameters with default values

# Parse named parameters
parse_params "$@"

# Print params passed

python -m pdb\
        splits.py \
        --source_url="XURLs.MIMIC4" \
        --data="mimic4_icd10_full" \
        --train_splits="[25, 50, 100]"
        # --train_splits="[25, 50, 100, 200, 400, 800, 1600, 3200, 4500, 6400, 9000, 12800, 18000, 25600, 36000, 49354]"