# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xcube',
                'doc_host': 'https://debjyotiSRoy.github.io',
                'git_url': 'https://github.com/debjyotiSRoy/xcube',
                'lib_path': 'xcube'},
  'syms': { 'xcube.imports': {},
            'xcube.utils': { 'xcube.utils.list_files': ('utils.html#list_files', 'xcube/utils.py'),
                             'xcube.utils.make_paths': ('utils.html#make_paths', 'xcube/utils.py'),
                             'xcube.utils.namestr': ('utils.html#namestr', 'xcube/utils.py'),
                             'xcube.utils.plot_hist': ('utils.html#plot_hist', 'xcube/utils.py'),
                             'xcube.utils.plot_reduction': ('utils.html#plot_reduction', 'xcube/utils.py')}}}
