# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xcube',
                'doc_host': 'https://debjyotiSRoy.github.io',
                'git_url': 'https://github.com/debjyotiSRoy/xcube',
                'lib_path': 'xcube'},
  'syms': { 'xcube.imports': {},
            'xcube.layers': { 'xcube.layers.LinBnDrop': ('layers.html#linbndrop', 'xcube/layers.py'),
                              'xcube.layers.LinBnDrop.__init__': ('layers.html#linbndrop.__init__', 'xcube/layers.py'),
                              'xcube.layers.XMLAttention': ('layers.html#xmlattention', 'xcube/layers.py'),
                              'xcube.layers.XMLAttention.__init__': ('layers.html#xmlattention.__init__', 'xcube/layers.py'),
                              'xcube.layers.XMLAttention.forward': ('layers.html#xmlattention.forward', 'xcube/layers.py')},
            'xcube.utils': { 'xcube.utils.list_files': ('utils.html#list_files', 'xcube/utils.py'),
                             'xcube.utils.make_paths': ('utils.html#make_paths', 'xcube/utils.py'),
                             'xcube.utils.namestr': ('utils.html#namestr', 'xcube/utils.py'),
                             'xcube.utils.plot_hist': ('utils.html#plot_hist', 'xcube/utils.py'),
                             'xcube.utils.plot_reduction': ('utils.html#plot_reduction', 'xcube/utils.py')}}}
