# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/19_text.callbacks.ipynb.

# %% auto 0
__all__ = ['LabelForcing']

# %% ../../nbs/19_text.callbacks.ipynb 1
from fastai.torch_imports import *
from fastai.torch_core import *
from fastai.callback.core import *
from fastcore.all import *
from ..imports import *
from ..metrics import *

# %% ../../nbs/19_text.callbacks.ipynb 6
class LabelForcing(Callback):
    def __init__(self, end_epoch):
        self.end_epoch = end_epoch
    
    @torch.no_grad()
    def after_pred(self):
        if self.training and self.epoch <= self.end_epoch:
            pred, attn, wgts = self.learn.pred
            pos = Tensor(self.y) == 1
            # pred[pos] += 3*pred.std()
            # pred[~pos] -= 3*pred.std()
            attn[pos] += attn[pos].std(dim=-1).unsqueeze(-1)
            attn[~pos] -= attn[~pos].std(dim=-1).unsqueeze(-1)
